### ISSUE TITLE
 Extend OS Installation Options for Machines

### ISSUE THREAD

**Issue by hardikdr** [ironcore-dev/metal-operator#145]
# Summary

Add support for multiple boot modes concerning how operating-system is installed on the Machine. 

- Installation of the OS directly on the disk.
- Installation of the OS in memory for the session.
- Preserving specific bind mounts post-boot.

### Progress Tracker:
- [x] Develop the initial version of the on-disk installation mechanism. @5kt 
- [x] Enhance the installer by integrating it with the initrd. @5kt 
- [x] Publish updated operating system images that include the new initrd. @hardikdr 
- [ ] Design and implement APIs for incorporating the installer into the Metal Operator. 

## Motivation

Better flexibility in deployment scenarios.

**Comment by hardikdr** [comment]
A possible enhancement in the APIs could look following, it's open for discussion: 

ServerClaim:
```yaml
apiVersion: metal.ironcore.dev/v1alpha1
kind: ServerClaim
metadata:
  name: example-serverclaim
spec:
  power: "On"
  ...
  bootPolicy: NetworkBootOnce   # Options: NetworkBootOnce / NetworkBootAlways / None
status:
  conditions:
    - type: NetworkBootedOnce
      status: "True"
      reason: Network boot was performed once.
```

- **`bootPolicy` Field in ServerClaim**: Add a `spec.bootPolicy` field with the following values:
  - **`NetworkBootOnce`**: Set `PXEBootOnce` signal for the first boot, and delete the associated `ServerBootConfig` after the server successfully boots.
  - **`NetworkBootAlways`**: Always set a `PXEBootOnce` signal during power cycles and retain the `ServerBootConfig`.
  - **`None`**: Do not set any boot-related signals, and do not create a `ServerBootConfig`.

- **`ServerBootConfig` Lifecycle**:
  - Delete `ServerBootConfig` after the first boot for `NetworkBootOnce`.
  - Retain `ServerBootConfig` indefinitely for `NetworkBootAlways`.
  - Skip creation of `ServerBootConfig` for `None`.

- **Tracking Boot State**:
  - Add a `NetworkBootedOnce` condition in `ServerClaim.status` to track if the network boot was successfully performed.


cc @5kt @defo89 @stefanhipfel @afritzler

**Comment by hardikdr** [comment]
### Update After the Last Meeting Discussion

#### API Changes in `ServerClaim`:
```yaml
apiVersion: metal.ironcore.dev/v1alpha1
kind: ServerClaim
metadata:
  name: example-serverclaim
spec:
  power: "On"
  ...
  bootPolicy: NetworkBootOnce   # Options: NetworkBootOnce / NetworkBootAlways / None
status:
  conditions:
    - type: NetworkBootedOnce
      status: "True"
      reason: Network boot was performed once.
```

### Summary:
- The `spec.bootPolicy` field allows users to define the boot behavior with three options:
  - `NetworkBootOnce`: Triggers a **PXE/Network boot on the first power cycle**. Once the signal has successfully been sent eg. no error is reported from BMC, the `status.conditions` field is updated to reflect `NetworkBootedOnce`, and all future power cycles **will not** include PXE boot signals.
  - `NetworkBootAlways`: Ensures **every power cycle** triggers a network boot by persistently setting the PXE/Network boot signal.
  - `None`: This is default option. No explicit network boot signals will be set. The server’s boot order will determine how it boots.
- Suggestions on naming conventions for `bootPolicy` values (`NetworkBootOnce`, `NetworkBootAlways`, `None`) and the exact `status.conditions` values are welcome.

Overall approach is open for further feedback.
