### ISSUE TITLE
Support Inline `Endpoint` Configuration for `BMC`

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/metal-operator#149]
# Summary

Currently, the `BMC` type uses an `EndpointRef` to reference external resources for endpoint information. This request proposes to add support for an inline configuration option, allowing users to directly specify access details within the `BMC` object itself.

The proposed solution introduces a new `Endpoint` struct within `BMCSpec`, providing flexibility for either inline or reference-based configuration. This feature will simplify configurations where the address details can be set directly in the `BMC` resource, without requiring an external reference.

## Acceptance Criteria

* Add the `Endpoint` struct with an Address field to `BMCSpec`.
* Implement validation to enforce mutual exclusivity between `EndpointRef` and `Endpoint`.
* Update the webhook to validate inline and reference-based configurations accurately.
* Test cases to verify correct behavior and validation.

## Example Usage

```
apiVersion: metal.ironcore.dev/v1alpha1
kind: BMC
metadata:
  name: example-bmc
spec:
  # Inline access configuration
  endpoint:
    ip: "192.168.1.10"
    macAddress: "aa:bb:cc:dd:ee"
  bmcSecretRef:
    name: bmc-credentials
  protocol:
    name: Redfish
    port: 443
```

## Additional Context

This feature enhances flexibility by allowing inline configuration for simpler setups while preserving the option to use `EndpointRef` for externally managed endpoints.
