### ISSUE TITLE
Ignition templating

### ISSUE THREAD

**Issue by xsen84** [ironcore-dev/metal-operator#191]
## Summary

Add functionality to the metal-operator to process and manage the generation of ignition secrets for ServerClaim objects. This feature will ensure that ignition secrets are derived from ignition templates and filled in with values computed by various ignition providers (e.g., networking, storage). The status of the ServerClaim will reflect the readiness state of the operation for each ignition provider.

## Example workflow for the feature:

1. A ServerClaim object is created:

ServerClaim:
```
apiVersion: metal.ironcore.dev/v1alpha1
kind: ServerClaim
metadata:
  name: somehostname-claim
spec:
  serverRef:
    name: somehostname-server
  serverSelector:
    cpu: 100
  ignitionProviders:
    - name: someprovider-networking
      spec:
        foo: bar
    - name: someprovider-storage
      spec:
        bar: foo
  ignitionRef:
    name: somehostname-ignition
  ignitionTemplateRef:
    name: someignition-template
```

2. The specified ignition template `someignition-template` will contain place holders to be updated, by operator,  with the computed values from the ignition providers.

3.  Ignition providers (e.g., someprovider-networking and someprovider-storage) will compute their values and update the valuesConfigRef.

4. Each controller will update the ServerClaim status to show the readiness state of each provider:
```
status:
  ignitionProviders:
    - name: someprovider-networking
      state: Ready
      valuesConfigRef:
        name: someprovider-networking-values
    - name: someprovider-storage
      state: Pending
  status: Bound
```
5. the operator will  merge/inject the computed values into the ignition template and create the an ignition secret. Also set the ServerClaim annotation to reflect the readiness state of the operation.

## Motivation

Streamline the process of generating ignition secrets for ServerClaim objects by dynamically populating values from ignition providers.
