### ISSUE TITLE
Introduce `ServerReboot` CRD as an Alternative to Annotation-Based Reboot

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/metal-operator#276]
### Feature Request
I propose adding a new Custom Resource Definition (CRD), tentatively named `ServerReboot`, to provide a declarative and structured way to initiate a bare metal server reboot in the `metal-operator`. This would serve as an alternative to the current annotation-based method (`metal.ironcore.dev/operation: reboot`).

### Motivation
Currently, rebooting a server is supported by setting the annotation `metal.ironcore.dev/operation: reboot` on a `Server` resource. While functional, this approach has limitations:
- It lacks a clear status tracking mechanism to monitor the reboot process.
- It’s less discoverable and harder to audit compared to a dedicated CRD.
- It doesn’t allow for additional configuration options (e.g., reboot type or timeout).

A `ServerReboot` CRD would:
- Provide a more Kubernetes-native, declarative interface for reboot operations.
- Enable status reporting and lifecycle tracking (e.g., Pending, InProgress, Completed, Failed).
- Improve usability by centralizing reboot-related logic in a dedicated resource.

### Proposed Solution
Introduce a `ServerReboot` CRD to initiate and manage server reboots. The operator would reconcile this resource by triggering the reboot via the existing BMC interaction logic, replacing the annotation-based trigger with a more robust workflow.

#### Example CRD Spec
```yaml
apiVersion: metal.ironcore.dev/v1alpha1
kind: ServerReboot
metadata:
  name: reboot-server-01
spec:
  serverRef:
    name: server-01  # References an existing Server resource
  rebootType: "hard" # Options: "soft" (graceful reboot) or "hard" (power cycle)
  timeout: "5m"     # Optional: Maximum time to wait for the reboot to complete
status:
  phase: "Pending"  # Possible values: Pending, InProgress, Completed, Failed
  lastUpdated: "2025-03-31T17:00:00Z"
  message: "Reboot request initiated"
```

#### Fields Description
- `spec.serverRef`: Links to an existing `Server` resource managed by the `metal-operator`.
- `spec.rebootType`: Specifies the reboot method (soft or hard).
- `spec.timeout`: Defines how long the operator should wait for the reboot to complete before marking it as failed (optional).
- `status.phase`: Tracks the current state of the reboot operation.
- `status.lastUpdated`: Timestamp of the last status update.
- `status.message`: Human-readable status or error message.

*Note*: Since there’s currently only one reboot method, I’ve omitted `rebootType` (soft/hard) from the spec, but this could be added later if more reboot options are introduced.

### Implementation Steps
1. **Define the CRD**: Create the `ServerReboot` CRD schema using Kubebuilder and register it in the `metal-operator`.
2. **Update the Controller**: Add reconciliation logic for `ServerReboot` resources, reusing the existing BMC reboot functionality triggered by the annotation.
3. **Status Reporting**: Implement status updates to reflect the reboot progress.
4. **Deprecation Plan**: Optionally, document the annotation-based reboot as deprecated in favor of the new CRD.
5. **Documentation**: Update the project docs with examples of using `ServerReboot`.
6. **Testing**: Add tests to verify the CRD works as expected and aligns with the existing reboot behavior.

### Additional Considerations
- Ensure compatibility with the existing annotation-based reboot mechanism during a transition period.
- Handle cases where both the annotation and CRD are used simultaneously (e.g., prioritize the CRD or fail with a clear error).
- Decide whether `ServerReboot` resources should auto-delete after completion or persist for auditing.

### Tasks
- [ ] Design and register the `ServerReboot` CRD.
- [ ] Implement reconciliation logic for `ServerReboot` in the controller.
- [ ] Reuse existing BMC reboot code for the CRD workflow.
- [ ] Add status reporting for the reboot process.
- [ ] Update documentation with `ServerReboot` examples.
- [ ] Add tests for the new CRD functionality.

### Open Questions
- Should the annotation-based reboot (`metal.ironcore.dev/operation: reboot`) be deprecated immediately or maintained as a legacy option?
- Should `ServerReboot` resources auto-delete after completion, or should this be configurable?
- Are there plans to support additional reboot types (e.g., soft vs. hard) that should be included in the initial design?
