### ISSUE TITLE
Add OoBMSetting CRD and Controller

### ISSUE THREAD

**Issue by nagadeesh-nagaraja** [ironcore-dev/metal-operator#287]
# Summary
Create a out-of-band-Management Settings CRD (named OoBMSetting) for BMC settings and implement the controller for it. 

for each vendor, the settings might be different.
Example for Dell:
redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/System.Embedded.1

will need enhancement to the bmc interface in the repo to be able to get, check and set bmc attributes for a given  vendor.

## Basic example (with DELL)

- **user** provides the settings as key value pair for strings.

- **Controller** gets the current values of the attributes provided by the user. with
"/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1"
 "/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/System.Embedded.1"
"/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/LifecycleController.Embedded.1"

- **Controller** checks the possible attributes, its type, values allowed with 
"redfish/v1/Registries/ManagerAttributeRegistry/ManagerAttributeRegistry.v1_0_0.json"

- **Controller** sets the attributes with "/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/System.Embedded.1/Settings"

Example CRD Spec

```
apiVersion: metal.ironcore.dev/v1alpha1
kind: OOBMSettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: oobmsettings-sample
spec:
  serverRef:
        name: server-01  # References an existing Server resource
 OoBMSetting:
        key1 : value1
        key2: value2
BMCRef:
        name: BMC-01  # References an existing BMC resource
ServerMaintenancePolicyTemplate:  # Policy an defined in  ServerMaintenance resource
serverMaintenanceRef:
          name: server-maintenance-01  # References an existing ServerMaintenance resource
status:
  state: "InSettingUpdate"  # overallStatus. Possible values: InSettingUpdate, InVersionUpgrade, SyncSettingsCompleted, Failed
  UpdateSettingState: "IssueSettingUpdate"    # State during. InSettingUpdate. Possible values:  WaitOnServerRebootPowerOff, IssueSettingUpdate, VerifySettingUpdate, WaitOnServerRebootPowerOn
```

## Motivation
Provide Ability to set BMC settings (outOfBandManagers Settings through controller)
