### ISSUE TITLE
Add `BIOSSettings` type to modify the BIOS settings of a `Server` 

### ISSUE THREAD

**Issue by nagadeesh-nagaraja** [ironcore-dev/metal-operator#288]
# Summary

Move Bios Setting out of server CRD and create a new CRD for bios settings.

Brief explanation of the feature.

## Basic example
**User** provides the settings as key value pair for strings.
**Controller** Read current Bios Settings and Version from the redfish
**Controller** checks the possible attributes, its type, values allowed.
**Controller**  Create a Maintenance object when Bios Settings require a reboot and take care of rebooting.
**Controller** sets the attributes with new Bios Settings

## Example CRD Spec

```yaml
apiVersion: metal.ironcore.dev/v1alpha1
kind: biossettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: biossettings-sample
spec:
  serverRef:
    name: endpoint-sample-system-0.  # References an existing Server resource
  bios:
    version: 2.10.2
    settings:
      PxeDev1EnDis: Enabled
  ServerMaintenancePolicyTemplate: OwnerApproval  # Policy an defined in  ServerMaintenance resource
  serverMaintenanceRef:
    name: server-maintenance-01  # References an existing ServerMaintenance resource
status:
  state: "InSettingUpdate"  # overallStatus. Possible values: InSettingUpdate, InVersionUpgrade, SyncSettingsCompleted, Failed
  UpdateSettingState: "IssueSettingUpdate"    # State during. InSettingUpdate. Possible values:  WaitOnServerRebootPowerOff, IssueSettingUpdate, VerifySettingUpdate, WaitOnServerRebootPowerOn
```

## Motivation

Currently the logic is within the server controller. free up the server controller and move the bios setting?upgrade to new controller and CRD.
