### ISSUE TITLE
Add BIOSVersion type and controller

### ISSUE THREAD

**Issue by nagadeesh-nagaraja** [ironcore-dev/metal-operator#305]
# Summary
Create a BIOSVersion CRD and implement the controller for it. 

Brief explanation of the feature.

## Basic example
**User** provides the BIOS version as strings.
**Controller** Read current Bios Version from the redfish
**Controller**  Create a Maintenance object when Bios Version requires changes 
**Controller** performs a version upgrade using REDFISH API 
**Controller** marks completed when version matches

## Example CRD Spec

```yaml
apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSVersion
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: biosversion-sample
spec:
  serverRef:
    name: endpoint-sample-system-0.  # References an existing Server resource
  bios:
    version: 2.10.3
    ImageURI: https://<ip/dns>:foos-2.10.3.bin
  ServerMaintenancePolicyTemplate: OwnerApproval  # Policy an defined in  ServerMaintenance resource
  serverMaintenanceRef:
    name: server-maintenance-01  # References an existing ServerMaintenance resource
status:
  state: "Upgrading"  # overallStatus. Possible values: Pending, Upgrading, Completed, Failed
```

## Motivation
Provide ability to upgrade the bios version to desired version.
