### ISSUE TITLE
Add `BMCVersion` type and controller

### ISSUE THREAD

**Issue by nagadeesh-nagaraja** [ironcore-dev/metal-operator#344]
# Summary
Create a BMCVersion CRD and implement the controller for it. 

Brief explanation of the feature.

## Basic example
**User** provides the BMC version as strings.
**Controller** Read current BMC Version from the redfish
**Controller**  Create a Maintenance object for server controller by this BMC when BMC Version requires changes 
**Controller** performs a version upgrade using REDFISH API 
**Controller** marks completed when version matches

## Example CRD Spec

```yaml
apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCVersion
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcversion-sample
spec:
  BMCRef:
    name: endpoint-sample  # References an existing BMC resource
  version: 2.10.3 # version to reach after upgrade
  UpdatePolicy : Force # this is to ask SimpleUpdate to skip checks
  image:
    URI: <protocol like https>://<ip/dns>:foos-2.10.3.bin
    imageSecretRef:
      Name: <Secret resource to access the URI>
    transferProtocol: <http/ftp/https> 
  ServerMaintenancePolicy: OwnerApproval  # Policy an defined in  ServerMaintenance resource
status:
  state: "Processing"  # overallStatus. Possible values: Pending, Processing, Completed, Failed
```

## Motivation
Provide ability to upgrade the BMC version to desired version.
