### ISSUE TITLE
Add `BIOSSettingSet` type and controller

### ISSUE THREAD

**Issue by nagadeesh-nagaraja** [ironcore-dev/metal-operator#349]
Create a Set for BIOSSetting to handle multiple server and sequence of setting at a time.

Example CRD Spec

```yaml
apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSSettingSet
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bios-setting-set-sample
spec:
  serverSelector:
    matchLabels:
       Manufacturer: a1
       Platform: foo
  version: 2.10.3 # version to reach after upgrade
  settingsList:
      -  # this is the first set of settings to apply
        PxeDev1EnDis: Enabled 
        PxeDev2EnDis: Enabled
      - # this is the additional settings to apply (added) to the above list after its been applied
        PxeDev1Interface: NIC-1-1
        PxeDev2Interface: NIC-2-1
  ServerMaintenancePolicy: OwnerApproval  # Policy an defined in  ServerMaintenance resource
status:
    ServerCount: 10  # is the number of server selected in the set.
    Pending: 5 # is the number of server biosSetting update is InProcess
    Failed: 2 # is the number of server biosSetting update has FAILED
    Completed: 3 # is the number of server biosSetting update has Completed
    State: "Processing"  # overallStatus. Possible values: Pending, Processing, Completed, Failed
```

workflow: 
- Given the selector field, all server matching that label will be selected to apply the specified list of settings. 
- the settings provided as list will be applied in that order.
    - example from above, `PxeDev1EnDis` and `PxeDev2EnDis` will be applied first before moving on to add additional settings (ie: `PxeDev1Interface` and `PxeDev2Interface`
- `BIOSSettingSet` will create `BIOSSettings` for each server selected. with settings map from the first list. 
- For all the `BIOSSettings` which get completed, the second list of settings will be Patched to `BIOSSettings` CRD. and the process is repeated until the list is exhausted. 
- For all the `BIOSSettings` which FAILED, the process will be stoped at the failed statge no further settings will be applied. 
- If `BIOSSettingSet` is changed, the process is started again, from the beginning of the list.  
- if `BIOSSettings` detects changes from its own settings to that of the physical server, it goes into `waiting` state, and `BIOSSettingSet` restarts the process of patching settings from the beginning of list.
    - The process is explained here:
        - assume the `BIOSSettings` is in applied state. ie: all the settings in from the list have been applied and are contained as a map[string][string] in this CRD.
        - `BIOSSettings` detects that the server settings do not match the current settings provided.
        - `BIOSSettings` moves state to `waiting`
        - `BIOSSettingSet` will patch the first set of settings from the list on `BIOSSettings` and these settings are applied. the hand-shake can be either through a state, annotation, or moving the state directly to `pending`
        - `BIOSSettings` moves state to `Applied`
        - `BIOSSettingSet` will patch (adds) the next set of settings to the `BIOSSettings` ... 
               - this can be done by comparing the key in dict of  `BIOSSettings` to check what is currently applied.
        - so on and so forth.
- `BIOSSettingSet` state moves state to the competed after all settings have been applied.
