### ISSUE TITLE
[Draft] BIOS/Firmware Update

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/metal-operator#99]
# Summary

Issue to discuss approaches on how we envision to perform BIOS and firmware update.

### Bulk update via central image

Perform a bulk update for all applicable components via a given image containing all the logic necessary to update the various components.

```
apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  name: foo-server
spec:
  firmware:
       manufacturer: ACME Corp.
       version: 2.0.0
status:
  firmware:
     manufacturer: ACME Corp.
     version: 1.0.0
```

### Individual components 

Expose the version information directly in the `Server` spec and let the `ServerReconciler` do the corresponding update operations.

```
apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  name: foo-server
spec:
  firmwares:
  - name: BIOS
    manufacturer: ACME Corp.
    version: 1.0.0
  - name: SSD
    manufacturer: ACME Corp.
    version: 2.0.0
  - name: NetworkInterfaceCard
    manufacturer: ACME Corp.
    version: 1.0.0
status:
  firmwares:
  - name: BIOS
    manufacturer: ACME Corp.
    version: 1.0.0
  - name: SSD
    manufacturer: ACME Corp.
    version: 2.0.0
  - name: NetworkInterfaceCard
    manufacturer: ACME Corp.
    version: 1.0.0
```

### Use a dedicated type to describe the updates

Define an own type describing the desired updates for a particular `Server` by referencing it via `.spec.serverRef`.

```
apiVersion: metal.ironcore.dev/v1alpha1
kind: ServerFirmware
metadata:
  name: foo-server
spec:
  serverRef:
    name: foo
  firmwares:
  - name: BIOS
    manufacturer: ACME Corp.
    version: 1.0.0
  - name: SSD
    manufacturer: ACME Corp.
    version: 2.0.0
  - name: NetworkInterfaceCard
    manufacturer: ACME Corp.
    version: 1.0.0
status:
  firmwares:
  - name: BIOS
    manufacturer: ACME Corp.
    version: 1.0.0
  - name: SSD
    manufacturer: ACME Corp.
    version: 2.0.0
  - name: NetworkInterfaceCard
    manufacturer: ACME Corp.
    version: 1.0.0
```
